---
- name: A simple Load Balanced AWS server
  hosts: localhost 
  connection: local
  gather_facts: False

  vars:
    region: us-east-1
    sg_name: Access_Web
    sg_descrip: Access_To_Web
    pem_key: POC-TEST-KEY
    instance_type: t2.micro
    ami_id: ami-591dda23
    instance_name: Ans-EC2
    subnet_id: subnet-0e7264961cd4775de
    ELB_Name: Ans-ELB

  tasks:
    - name: Create security group
      ec2_group:
        name: "{{ sg_name }}"
        description: "{{ sg_descrip }}"
        region: "{{ region }}"
        rules:
          - proto: tcp  # ssh
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # http
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp  # https
            from_port: 443
            to_port: 443
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: web_firewall

    - name: Create an EC2 instance
      ec2:
        key_name: "{{ pem_key }}"
        region: "{{ region }}"
        group_id: "{{ web_firewall.group_id }}"
        instance_type: "{{ instance_type }}"
        image: "{{ ami_id }}"
        wait: yes
        instance_tags:
            env: "{{ instance_name }}"
        count_tag: name
        exact_count: 1
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
      register: ec2

    - name: wait for the servers to appear on the network
      wait_for: host={{ item.public_dns_name }} port=22 delay=180 timeout=180 state=started
      with_items: ec2.tagged_instances

    - name: add server ip addresses to hosts group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.tagged_instances

- name: webservers (installs nginx ...)
  hosts: launched
  remote_user: ec2-user
  become: true
  become_method: sudo
  gather_facts: True

- name: spin up the load balancer and add the servers to it
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: setup a simple load balancer
      ec2_elb_lb:
        name: "{{ ELB_Name }}"
        state: present
        region: "{{ region }}"
        zones:
          - us-east-1a
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: ELB_Name

    - name: add the webservers to the load balancer
      local_action: ec2_elb
      args:
        instance_id: "{{ item.id }}"
        ec2_elbs: "{{ ELB_Name }}"
        state: present
        region: us-east-1
      with_items: ec2.tagged_instances
